const data = [
    {
        id : 1,
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "коллекции",
        "season" : "лето",
        "price" : "10",
        "rarity" : "5",
        "img" : "https://ae04.alicdn.com/kf/Hdb232e7f2b164285935a377ef72a2eb0l.jpg_350x350.jpg",
    },
    {
        id : 2,
        "for" : "жене",
        "developments" : "для себя",
        "collection" : "браслет",
        "season" : "зима",
        "price" : "30",
        "rarity" : "10",
        "img" : "https://tangogold.com.ua/content/goods/4921/picture-4921.jpg",
    },
    {
        id : 3,
        "for" : "партнеру",
        "developments" : "день рождения",
        "collection" : "цыпочка",
        "season" : "весна",
        "price" : "50",
        "rarity" : "8",
        "img" : "https://basket-02.wb.ru/vol173/part17366/17366823/images/big/2.jpg",
    },
    {
        id : 4,
        "for" : "папе",
        "developments" : "для себя",
        "collection" : "браслет",
        "season" : "осень",
        "price" : "100",
        "rarity" : "5",
        "img" : "https://images.prom.ua/2430115448_w640_h640_muzhskoj-shirokij-braslet.jpg",
    },
    {
        id : 5,
        "for" : "маме",
        "developments" : "день рождения",
        "collection" : "серьги",
        "season" : "лето",
        "price" : "200",
        "rarity" : "3",
        "img" : "https://7karat.by/upload/medialibrary/f2d/f2d6fbb7966e25ba1bc36fdedb20d96e.png",
    },
    {
        id : 6,
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "коллекции",
        "season" : "весна",
        "price" : "20",
        "rarity" : "7",
        "img" : "https://diamant.ua/uploads/a0/37/a037cdec2d172730ce176586495a588f.jpg",
    },
    {
        id : 7,
        "for" : "жене",
        "developments" : "свадьба",
        "collection" : "серьги",
        "season" : "лето",
        "price" : "250",
        "rarity" : "7",
        "img" : "https://www.alltime.ru/obj/article/image-blog/wedding-earrings/wedding-earrings_2.jpg",
    },
    {
        id : 8,
        "for" : "мужу",
        "developments" : "день рождение",
        "collection" : "браслет",
        "season" : "осень",
        "price" : "50",
        "rarity" : "8",
        "img" : "https://www.alltime.ru/obj/article/image-blog/mozhno_li_darit_braslet/mozhno_li_darit_braslet_2.jpg",
    },
    {
        id : 9,
        "for" : "маме",
        "developments" : "день рождение",
        "collection" : "коллекции",
        "season" : "весна",
        "price" : "120",
        "rarity" : "10",
        "img" : "https://ae04.alicdn.com/kf/Hb0e9c9c09b76460480d8bdb2c8e4a599a/-.jpg_640x640.jpg",
    },
    {
        id : 10,
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "коллекции",
        "season" : "весна",
        "price" : "50",
        "rarity" : "7",
        "img" : "https://bgs.kiev.ua/wp-content/uploads/Razmery-obruchalnykh-kolets-87-Bz.jpg",
    },

]

